replicaCount: 2


image:
  repository: ghcr.io/bu3lii/cicd-go-k8s
  tag: 75757a4a1aee4cfab7499615cc15a033deba2a50
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

containerPort: 8080

probes:
  liveness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10

  readiness:
    path: /ready
    initialDelaySeconds: 2
    periodSeconds: 5