replicaCount: 2


image:
  repository: ghcr.io/bu3lii/cicd-go-k8s
  tag: 2ac7b9ea173472aecb124ebad6849c740751f1f1
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

containerPort: 8080

probes:
  liveness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10

  readiness:
    path: /ready
    initialDelaySeconds: 2
    periodSeconds: 5