name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: Check formatting
        run: |
          test -z "$(gofmt -l .)"

      - name: Run go vet
        run: go vet ./...

      - name: Run tests
        run: go test ./...

      - name: Build application
        run: go build -o server ./cmd/api

      - name: Log in to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: docker build -t cicd-go-k8s:${{ github.sha }} .

      - name: Build and push Docker image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/bu3lii/cicd-go-k8s:${{ github.sha }}
            ghcr.io/bu3lii/cicd-go-k8s:latest

      - name: Update Helm image tag
        if: github.event_name == 'push'
        run: |
          sed -i "s/tagL .*/tag: ${{ github.sha }}/" helm/go-api/values.yaml

          git config user.name "github-actions[bot]""
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add helm/go-api/values.yaml
          git commit -m "chore: deploy ${{github.sha}} [skip ci]"
          git push
